// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/apis/demo/v1alpha1"
	scheme "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HellosGetter has a method to return a HelloInterface.
// A group's client should implement this interface.
type HellosGetter interface {
	Hellos(namespace string) HelloInterface
}

// HelloInterface has methods to work with Hello resources.
type HelloInterface interface {
	Create(*v1alpha1.Hello) (*v1alpha1.Hello, error)
	Update(*v1alpha1.Hello) (*v1alpha1.Hello, error)
	UpdateStatus(*v1alpha1.Hello) (*v1alpha1.Hello, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Hello, error)
	List(opts v1.ListOptions) (*v1alpha1.HelloList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Hello, err error)
	HelloExpansion
}

// hellos implements HelloInterface
type hellos struct {
	client rest.Interface
	ns     string
}

// newHellos returns a Hellos
func newHellos(c *DemoV1alpha1Client, namespace string) *hellos {
	return &hellos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hello, and returns the corresponding hello object, and an error if there is any.
func (c *hellos) Get(name string, options v1.GetOptions) (result *v1alpha1.Hello, err error) {
	result = &v1alpha1.Hello{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hellos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Hellos that match those selectors.
func (c *hellos) List(opts v1.ListOptions) (result *v1alpha1.HelloList, err error) {
	result = &v1alpha1.HelloList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hellos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hellos.
func (c *hellos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hellos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a hello and creates it.  Returns the server's representation of the hello, and an error, if there is any.
func (c *hellos) Create(hello *v1alpha1.Hello) (result *v1alpha1.Hello, err error) {
	result = &v1alpha1.Hello{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hellos").
		Body(hello).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hello and updates it. Returns the server's representation of the hello, and an error, if there is any.
func (c *hellos) Update(hello *v1alpha1.Hello) (result *v1alpha1.Hello, err error) {
	result = &v1alpha1.Hello{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hellos").
		Name(hello.Name).
		Body(hello).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hellos) UpdateStatus(hello *v1alpha1.Hello) (result *v1alpha1.Hello, err error) {
	result = &v1alpha1.Hello{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hellos").
		Name(hello.Name).
		SubResource("status").
		Body(hello).
		Do().
		Into(result)
	return
}

// Delete takes name of the hello and deletes it. Returns an error if one occurs.
func (c *hellos) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hellos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hellos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hellos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hello.
func (c *hellos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Hello, err error) {
	result = &v1alpha1.Hello{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hellos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
