// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HelloListerExpansion allows custom methods to be added to
// HelloLister.
type HelloListerExpansion interface{}

// HelloNamespaceListerExpansion allows custom methods to be added to
// HelloNamespaceLister.
type HelloNamespaceListerExpansion interface{}
