// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/apis/demo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHellos implements HelloInterface
type FakeHellos struct {
	Fake *FakeDemoV1alpha1
	ns   string
}

var hellosResource = schema.GroupVersionResource{Group: "demo.wso2.com", Version: "v1alpha1", Resource: "hellos"}

var hellosKind = schema.GroupVersionKind{Group: "demo.wso2.com", Version: "v1alpha1", Kind: "Hello"}

// Get takes name of the hello, and returns the corresponding hello object, and an error if there is any.
func (c *FakeHellos) Get(name string, options v1.GetOptions) (result *v1alpha1.Hello, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hellosResource, c.ns, name), &v1alpha1.Hello{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Hello), err
}

// List takes label and field selectors, and returns the list of Hellos that match those selectors.
func (c *FakeHellos) List(opts v1.ListOptions) (result *v1alpha1.HelloList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hellosResource, hellosKind, c.ns, opts), &v1alpha1.HelloList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HelloList{ListMeta: obj.(*v1alpha1.HelloList).ListMeta}
	for _, item := range obj.(*v1alpha1.HelloList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hellos.
func (c *FakeHellos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hellosResource, c.ns, opts))

}

// Create takes the representation of a hello and creates it.  Returns the server's representation of the hello, and an error, if there is any.
func (c *FakeHellos) Create(hello *v1alpha1.Hello) (result *v1alpha1.Hello, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hellosResource, c.ns, hello), &v1alpha1.Hello{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Hello), err
}

// Update takes the representation of a hello and updates it. Returns the server's representation of the hello, and an error, if there is any.
func (c *FakeHellos) Update(hello *v1alpha1.Hello) (result *v1alpha1.Hello, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hellosResource, c.ns, hello), &v1alpha1.Hello{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Hello), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHellos) UpdateStatus(hello *v1alpha1.Hello) (*v1alpha1.Hello, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hellosResource, "status", c.ns, hello), &v1alpha1.Hello{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Hello), err
}

// Delete takes name of the hello and deletes it. Returns an error if one occurs.
func (c *FakeHellos) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hellosResource, c.ns, name), &v1alpha1.Hello{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHellos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hellosResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HelloList{})
	return err
}

// Patch applies the patch and returns the patched hello.
func (c *FakeHellos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Hello, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hellosResource, c.ns, name, data, subresources...), &v1alpha1.Hello{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Hello), err
}
