// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	demo_v1alpha1 "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/apis/demo/v1alpha1"
	versioned "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/client/clientset/versioned"
	internalinterfaces "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/isurulucky/k8sday/03-advanced-kubernetes/pkg/client/listers/demo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HelloInformer provides access to a shared informer and lister for
// Hellos.
type HelloInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HelloLister
}

type helloInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHelloInformer constructs a new informer for Hello type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHelloInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHelloInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHelloInformer constructs a new informer for Hello type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHelloInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().Hellos(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().Hellos(namespace).Watch(options)
			},
		},
		&demo_v1alpha1.Hello{},
		resyncPeriod,
		indexers,
	)
}

func (f *helloInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHelloInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *helloInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&demo_v1alpha1.Hello{}, f.defaultInformer)
}

func (f *helloInformer) Lister() v1alpha1.HelloLister {
	return v1alpha1.NewHelloLister(f.Informer().GetIndexer())
}
